# Generated by Django 3.0.6 on 2020-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tut11', '0002_physiccomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=100)),
                ('title', models.CharField(default='', max_length=500)),
                ('desc', models.CharField(default='', max_length=5000)),
                ('videoFile', models.FileField(upload_to='tut11/chemistry/', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='physic',
            name='videoFile',
            field=models.FileField(upload_to='tut11/physic/', verbose_name=''),
        ),
    ]
