# Generated by Django 3.0.6 on 2020-06-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=70)),
                ('Class', models.CharField(max_length=12)),
                ('Section', models.CharField(max_length=5)),
                ('Message', models.TextField()),
                ('DateStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
